def success() {
    def imageUrl = 'https://semaphoreci.com/wp-content/uploads/2020/02/cic-cd-explained.jpg'
    def imageWidth = '800px'
    def imageHeight = 'auto'

    echo "Sending success email..."
    emailext(
        body: """
        <html>
        <body>
            <p>YEEEEY, The Jenkins job was successful.</p>
            <p>You can view the build at: <a href="${BUILD_URL}">${BUILD_URL}</a></p>
            <p><img src="${imageUrl}" alt="Your Image" width="${imageWidth}" height="${imageHeight}"></p>
        </body>
        </html>
        """,
        subject: "Jenkins Build - Success",
        to: 'oumayma.cherif@esprit.tn',
        from: 'oumayma.cherif@esprit.tn',
        replyTo: 'oumayma.cherif@esprit.tn',
        mimeType: 'text/html'
    )
    echo "Success email sent."
}

def failure() {
    def imageUrl = 'https://miro.medium.com/v2/resize:fit:4800/format:webp/1*ytlj68SIRGvi9mecSDb52g.png'
    def imageWidth = '800px'
    def imageHeight = 'auto'

    echo "Sending failure email..."
    emailext(
        body: """
        <html>
        <body>
            <p>eewww, The Jenkins job Failed.</p>
            <p>You can view the build at: <a href="${BUILD_URL}">${BUILD_URL}</a></p>
            <p><img src="${imageUrl}" alt="Your Image" width="${imageWidth}" height="${imageHeight}"></p>
        </body>
        </html>
        """,
        subject: "Jenkins Build - Failure",
        to: 'oumayma.cherif@esprit.tn',
        from: 'oumayma.cherif@esprit.tn',
        replyTo: 'oumayma.cherif@esprit.tn',
        mimeType: 'text/html'
    )
    echo "Failure email sent."
}


   pipeline {
    agent any

    tools {
        jdk 'JAVA_HOME'
        maven 'MAVEN_HOME'
    }

    environment {
        NEXUS_CREDENTIALS = credentials('nexus-credentials')
        GITHUB_CREDENTIALS = credentials('github')
        SONAR_TOKEN = credentials('sonar.token')
        DOCKER_HUB_CREDENTIALS = credentials('docker-hub')
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }

    stages {
        stage("Cleanup Workspace") {
            steps {
                cleanWs()
            }
        }

        stage("Checkout from SCM") {
            steps {
                git branch: 'main',
                credentialsId: 'github',
                url: 'https://github.com/Oumayma-cherif/Devops.git'
            }
        }

        stage("Build Backend Application") {
            steps {
                sh "mvn clean package -DskipTests"
            }
        }

        stage("SonarQube Analysis") {
            steps {
                script {
                    // Start SonarQube service if not running
                    sh 'docker start sonarqube || echo "SonarQube already running."'

                    // Wait for SonarQube to be operational
                    sh '''
                    echo "Waiting for SonarQube to be operational..."
                    until curl -s http://localhost:9000/api/system/status | grep -q "UP"; do
                        echo "SonarQube is not ready, waiting for 10 seconds..."
                        sleep 10
                    done
                    echo "SonarQube is now ready!"
                    '''

                    // Run SonarQube analysis with the correct token
                    sh "mvn sonar:sonar -Dsonar.projectKey=gestion-station-ski -Dsonar.host.url=http://localhost:9000 -Dsonar.login=${SONAR_TOKEN}"
                }
            }
        }

        stage("Nexus Deployment") {
            steps {
                script {
                    //Start Nexus service if not running
                    sh 'docker start nexus || echo "Nexus already running."'

                    // Wait for Nexus to be operational
                    sh 'sleep 10'

                    // Deploy to Nexus
                    sh "mvn clean deploy -DskipTests -s /var/lib/jenkins/.m2/settings.xml"
                }
            }
        }

        stage("Build Backend Docker Image") {
            steps {
                script {
                    // Build the backend Docker image
                    sh "docker build -t oumayy/gestion-devops-backend:${IMAGE_TAG} ."
                }
            }
        }

        stage("Build Frontend Docker Image") {
            steps {
                script {
                    // Build the frontend Docker image (with Nginx serving the built Angular app)
                    sh "docker build -t oumayy/gestion-devops-frontend:${IMAGE_TAG} ./frontend"
                }
            }
        }

        stage("Publish Docker Images") {
            steps {
                script {
                    // Explicitly log in to Docker Hub
                    sh "echo ${DOCKER_HUB_CREDENTIALS_PSW} | docker login -u ${DOCKER_HUB_CREDENTIALS_USR} --password-stdin"

                    // Push the backend Docker image
                    sh "docker push oumayy/gestion-devops-backend:${IMAGE_TAG}"

                    // Push the frontend Docker image
                    sh "docker push oumayy/gestion-devops-frontend:${IMAGE_TAG}"
                }
            }
        }

        stage("Start Services with Docker Compose") {
            steps {
                script {
                    dir("${WORKSPACE}") {  // This will ensure it runs from the root directory of the project
                        sh "docker-compose up -d"
                    }
                }
            }
        }

        stage("Email Notification") {
            steps {
                script {
                    currentBuild.resultIsBetterOrEqualTo('SUCCESS') ? success() : failure()
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
